import os
import re
import psycopg2
from psycopg2 import pool
import logging
from datetime import datetime
from flask import Flask, request, abort
from linebot import LineBotApi, WebhookHandler
from linebot.exceptions import InvalidSignatureError, LineBotApiError
from linebot.models import (
    MessageEvent, TextMessage, TextSendMessage, JoinEvent, FollowEvent,
    QuickReply, QuickReplyButton, MessageAction
)

logging.basicConfig(level=logging.INFO)
app = Flask(__name__)

LINE_CHANNEL_ACCESS_TOKEN = os.environ.get('LINE_CHANNEL_ACCESS_TOKEN')
LINE_CHANNEL_SECRET = os.environ.get('LINE_CHANNEL_SECRET')
DATABASE_URL = os.environ.get('DATABASE_URL')

line_bot_api = LineBotApi(LINE_CHANNEL_ACCESS_TOKEN)
handler = WebhookHandler(LINE_CHANNEL_SECRET)

connection_pool = None

def get_connection_pool():
    global connection_pool
    if connection_pool is None:
        connection_pool = psycopg2.pool.SimpleConnectionPool(1, 10, DATABASE_URL)
    return connection_pool

def get_db_connection():
    try:
        pool = get_connection_pool()
        return pool.getconn()
    except Exception as e:
        app.logger.error(f"連線池錯誤，使用直接連線: {e}")
        return psycopg2.connect(DATABASE_URL)

def return_db_connection(conn):
    try:
        pool = get_connection_pool()
        pool.putconn(conn)
    except:
        if conn:
            conn.close()

WELCOME_MSG = (
    "👋 大家好！我是情侶記帳小幫手\n\n"
    "✨ 初次見面請先註冊：\n"
    "👉 輸入「我是 你的名字」\n"
    "(例如：我是 老公)\n\n"
    "📝 【指令大全】\n"
    "1. 記自己 (最常用)：\n"
    "   • 晚餐 200\n"
    "   • 飲料50 (不用空格)\n\n"
    "2. 自動拆帳：\n"
    "   • 晚餐 400 幫 150\n\n"
    "3. 結算與查詢：\n"
    "   • 結算：看簡易統計與欠款\n"
    "   • 詳細結算：看所有消費明細\n"
    "   • 老公 結算：只看老公的\n\n"
    "4. 修改與刪除：\n"
    "   • 移除 飲料：刪除最新一筆「飲料」\n"
    "   • 移除最後一筆：刪除剛剛記的那筆\n"
    "   • 清除：全部刪光光\n\n"
    "💡 使用下方快速按鈕更方便！"
)

def create_quick_reply_buttons():
    buttons = [
        QuickReplyButton(action=MessageAction(label="結算", text="結算")),
        QuickReplyButton(action=MessageAction(label="說明", text="說明")),
        QuickReplyButton(action=MessageAction(label="移除最後一筆", text="移除最後一筆"))
    ]
    
    try:
        conn = get_db_connection()
        cur = conn.cursor()
        cur.execute("SELECT display_name FROM users ORDER BY user_id LIMIT 2")
        users = cur.fetchall()
        cur.close()
        return_db_connection(conn)
        
        for user in users:
            user_name = user[0]
            buttons.append(
                QuickReplyButton(
                    action=MessageAction(label=f"{user_name} 結算", text=f"{user_name} 結算")
                )
            )
    except Exception as e:
        app.logger.error(f"建立快速按鈕失敗: {e}")
    
    return QuickReply(items=buttons)

_db_initialized = False

def init_db():
    global _db_initialized
    if _db_initialized:
        return
        
    try:
        conn = get_db_connection()
        cur = conn.cursor()
        
        cur.execute("""
            CREATE TABLE IF NOT EXISTS users (
                user_id TEXT PRIMARY KEY,
                display_name TEXT NOT NULL
            );
        """)
        
        cur.execute("""
            CREATE TABLE IF NOT EXISTS expenses (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                user_id TEXT NOT NULL,
                item TEXT NOT NULL,
                amount INTEGER NOT NULL,
                created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('asia/taipei', now())
            );
        """)
        
        cur.execute("CREATE INDEX IF NOT EXISTS idx_expenses_user_id ON expenses(user_id);")
        cur.execute("CREATE INDEX IF NOT EXISTS idx_expenses_created_at ON expenses(created_at);")
        cur.execute("CREATE INDEX IF NOT EXISTS idx_expenses_user_created ON expenses(user_id, created_at);")
        
        conn.commit()
        cur.close()
        return_db_connection(conn)
        _db_initialized = True
        app.logger.info("資料庫初始化完成！")
    except Exception as e:
        app.logger.error(f"資料庫初始化失敗: {e}")
        if conn:
            return_db_connection(conn)

def get_user_name(user_id, conn=None):
    should_close = False
    if conn is None:
        conn = get_db_connection()
        should_close = True
    
    try:
        cur = conn.cursor()
        cur.execute("SELECT display_name FROM users WHERE user_id = %s", (user_id,))
        result = cur.fetchone()
        cur.close()
        
        if result:
            return result[0]
    except Exception as e:
        app.logger.error(f"查詢使用者名稱失敗: {e}")
    finally:
        if should_close:
            return_db_connection(conn)
    
    try:
        profile = line_bot_api.get_profile(user_id)
        return profile.display_name
    except:
        return f"用戶({user_id[:4]})"

def get_user_id_by_name(name):
    conn = None
    try:
        conn = get_db_connection()
        cur = conn.cursor()
        cur.execute("SELECT user_id FROM users WHERE display_name = %s", (name,))
        result = cur.fetchone()
        cur.close()
        if result:
            return result[0]
    except Exception as e:
        app.logger.error(f"查詢 ID 失敗: {e}")
    finally:
        if conn:
            return_db_connection(conn)
    return None

def get_partner_id(my_user_id):
    conn = None
    try:
        conn = get_db_connection()
        cur = conn.cursor()
        cur.execute("SELECT user_id, display_name FROM users WHERE user_id != %s", (my_user_id,))
        rows = cur.fetchall()
        cur.close()
        
        if len(rows) == 1:
            return rows[0][0], rows[0][1]
    except Exception as e:
        app.logger.error(f"查詢另一半失敗: {e}")
    finally:
        if conn:
            return_db_connection(conn)
    return None, None

def calculate_debts(conn):
    """
    計算欠款關係
    返回: {debtor_name: {creditor_name: amount}}
    """
    try:
        cur = conn.cursor()
        
        # 獲取所有使用者映射
        cur.execute("SELECT user_id, display_name FROM users")
        users = {row[0]: row[1] for row in cur.fetchall()}
        
        # 查找所有包含 "(需給XXX)" 的項目
        cur.execute("""
            SELECT user_id, item, amount
            FROM expenses
            WHERE item LIKE '%(需給%)'
        """)
        
        debt_records = cur.fetchall()
        cur.close()
        
        # 初始化欠款字典
        debts = {}
        
        # 解析每筆欠款記錄
        for user_id, item, amount in debt_records:
            # 提取債權人名字 (從 "項目 (需給XXX)" 中提取 XXX)
            match = re.search(r'\(需給(.+?)\)', item)
            if match:
                creditor_name = match.group(1)
                debtor_name = users.get(user_id, user_id)
                
                # 初始化債務人字典
                if debtor_name not in debts:
                    debts[debtor_name] = {}
                
                # 累加欠款
                if creditor_name not in debts[debtor_name]:
                    debts[debtor_name][creditor_name] = 0
                debts[debtor_name][creditor_name] += amount
        
        return debts
        
    except Exception as e:
        app.logger.error(f"計算欠款失敗: {e}")
        return {}

@app.route("/callback", methods=['POST'])
def callback():
    init_db()
    
    signature = request.headers.get('X-Line-Signature', '')
    body = request.get_data(as_text=True)
    app.logger.info(f"Request body: {body}")

    try:
        handler.handle(body, signature)
    except InvalidSignatureError:
        app.logger.error("Invalid signature.")
        abort(400)
    return 'OK'

@handler.add(FollowEvent)
def handle_follow(event):
    line_bot_api.reply_message(
        event.reply_token, 
        TextSendMessage(text=WELCOME_MSG, quick_reply=create_quick_reply_buttons())
    )

@handler.add(JoinEvent)
def handle_join(event):
    line_bot_api.reply_message(
        event.reply_token, 
        TextSendMessage(text=WELCOME_MSG, quick_reply=create_quick_reply_buttons())
    )

@handler.add(MessageEvent, message=TextMessage)
def handle_message(event):
    msg = event.message.text.strip()
    sender_id = event.source.user_id

    if msg == "我愛你":
        line_bot_api.reply_message(
            event.reply_token, 
            TextSendMessage(text="我也愛你們爸爸媽媽 ❤️", quick_reply=create_quick_reply_buttons())
        )
        return

    if msg in ["說明", "指令", "help", "Help"]:
        line_bot_api.reply_message(
            event.reply_token, 
            TextSendMessage(text=WELCOME_MSG, quick_reply=create_quick_reply_buttons())
        )
        return
    
    if msg.startswith("我是"):
        name = msg[2:].strip()
        if name:
            conn = None
            try:
                conn = get_db_connection()
                cur = conn.cursor()
                cur.execute("""
                    INSERT INTO users (user_id, display_name) 
                    VALUES (%s, %s)
                    ON CONFLICT (user_id) 
                    DO UPDATE SET display_name = EXCLUDED.display_name;
                """, (sender_id, name))
                conn.commit()
                cur.close()
                line_bot_api.reply_message(
                    event.reply_token, 
                    TextSendMessage(text=f"✅ 歡迎 {name}！已記住你的名字。", quick_reply=create_quick_reply_buttons())
                )
            except Exception as e:
                app.logger.error(f"設定名字失敗: {e}")
                line_bot_api.reply_message(
                    event.reply_token, 
                    TextSendMessage(text="❌ 設定失敗，請稍後再試。", quick_reply=create_quick_reply_buttons())
                )
            finally:
                if conn:
                    return_db_connection(conn)
        return

    if msg == "移除最後一筆":
        conn = None
        try:
            conn = get_db_connection()
            cur = conn.cursor()
            cur.execute("SELECT id, user_id, amount, item, created_at FROM expenses ORDER BY created_at DESC LIMIT 1")
            row = cur.fetchone()
            if row:
                cur.execute("DELETE FROM expenses WHERE id = %s", (row[0],))
                conn.commit()
                name = get_user_name(row[1], conn)
                date_str = row[4].strftime("%m/%d")
                reply_text = f"🗑️ 已移除最新一筆紀錄：\n{date_str} {name}: {row[3]} ${row[2]}"
            else:
                reply_text = "📭 目前沒有任何紀錄可以移除喔！"
            cur.close()
            line_bot_api.reply_message(
                event.reply_token, 
                TextSendMessage(text=reply_text, quick_reply=create_quick_reply_buttons())
            )
        except Exception as e:
            app.logger.error(f"DB Error: {e}")
            line_bot_api.reply_message(
                event.reply_token,
                TextSendMessage(text="❌ 移除失敗，請稍後再試。", quick_reply=create_quick_reply_buttons())
            )
        finally:
            if conn:
                return_db_connection(conn)
        return

    match_remove = re.match(r'^移除\s+(.+)$', msg)
    if match_remove:
        item_to_remove = match_remove.group(1).strip()
        conn = None
        try:
            conn = get_db_connection()
            cur = conn.cursor()
            cur.execute("""
                SELECT id, user_id, amount, created_at 
                FROM expenses 
                WHERE item = %s 
                ORDER BY created_at DESC 
                LIMIT 1
            """, (item_to_remove,))
            row = cur.fetchone()
            
            if row:
                cur.execute("DELETE FROM expenses WHERE id = %s", (row[0],))
                conn.commit()
                name = get_user_name(row[1], conn)
                date_str = row[3].strftime("%m/%d")
                reply_text = f"🗑️ 已移除：\n{date_str} {name}: {item_to_remove} ${row[2]}"
            else:
                reply_text = f"❌ 找不到名稱為「{item_to_remove}」的紀錄！"
            
            cur.close()
            line_bot_api.reply_message(
                event.reply_token, 
                TextSendMessage(text=reply_text, quick_reply=create_quick_reply_buttons())
            )
        except Exception as e:
            app.logger.error(f"DB Error: {e}")
            line_bot_api.reply_message(
                event.reply_token,
                TextSendMessage(text="❌ 移除失敗，請稍後再試。", quick_reply=create_quick_reply_buttons())
            )
        finally:
            if conn:
                return_db_connection(conn)
        return

    pattern_split_explicit = r'^(?:(\d{4}[-/]\d{1,2}[-/]\d{1,2})\s*)?(.+?)\s*(\d+)\s*幫\s*(.+?)\s*(\d+)$'
    pattern_split_implicit = r'^(?:(\d{4}[-/]\d{1,2}[-/]\d{1,2})\s*)?(.+?)\s*(\d+)\s*幫\s*(\d+)$'
    
    match_explicit = re.match(pattern_split_explicit, msg)
    match_implicit = re.match(pattern_split_implicit, msg)
    
    if match_explicit or match_implicit:
        target_user_id = None
        target_user_name = None
        sender_name = get_user_name(sender_id)

        if match_implicit:
            date_str = match_implicit.group(1)
            item = match_implicit.group(2).strip()
            total_amount = int(match_implicit.group(3))
            split_amount = int(match_implicit.group(4))
            
            target_user_id, target_user_name = get_partner_id(sender_id)
            if not target_user_id:
                line_bot_api.reply_message(
                    event.reply_token, 
                    TextSendMessage(
                        text="❌ 無法自動判斷對象！\n如果是多人使用，請指定名字：\n例如：晚餐 400 幫 老公 150",
                        quick_reply=create_quick_reply_buttons()
                    )
                )
                return
        elif match_explicit:
            date_str = match_explicit.group(1)
            item = match_explicit.group(2).strip()
            total_amount = int(match_explicit.group(3))
            target_name_input = match_explicit.group(4).strip()
            split_amount = int(match_explicit.group(5))
            
            target_user_id = get_user_id_by_name(target_name_input)
            if target_user_id:
                target_user_name = target_name_input
            else:
                line_bot_api.reply_message(
                    event.reply_token, 
                    TextSendMessage(
                        text=f"❌ 找不到「{target_name_input}」！\n請確認對方有輸入「我是 {target_name_input}」註冊過。",
                        quick_reply=create_quick_reply_buttons()
                    )
                )
                return

        self_amount = total_amount - split_amount
        created_at_val = "now()"
        display_date = "今天"
        if date_str:
            try:
                datetime.strptime(date_str, "%Y-%m-%d")
                created_at_val = f"'{date_str} 12:00:00'"
                display_date = date_str
            except ValueError:
                line_bot_api.reply_message(
                    event.reply_token, 
                    TextSendMessage(text="❌ 日期格式請用 YYYY-MM-DD", quick_reply=create_quick_reply_buttons())
                )
                return

        conn = None
        try:
            conn = get_db_connection()
            cur = conn.cursor()
            
            sql = "INSERT INTO expenses (user_id, item, amount, created_at) VALUES (%s, %s, %s, " + created_at_val + ")" if created_at_val != "now()" else "INSERT INTO expenses (user_id, item, amount) VALUES (%s, %s, %s)"
            
            cur.execute(sql, (sender_id, item, self_amount))
            note_item = f"{item} (需給{sender_name})"
            cur.execute(sql, (target_user_id, note_item, split_amount))
            
            conn.commit()
            cur.close()
            
            reply_text = (
                f"✅ 自動拆帳完成！\n"
                f"📅 時間：{display_date}\n"
                f"🛒 項目：{item} (總額 ${total_amount})\n"
                f"----------------\n"
                f"👤 {sender_name}：${self_amount}\n"
                f"👤 {target_user_name}：${split_amount}"
            )
            line_bot_api.reply_message(
                event.reply_token, 
                TextSendMessage(text=reply_text, quick_reply=create_quick_reply_buttons())
            )
            
        except Exception as e:
            app.logger.error(f"DB Error: {e}")
            line_bot_api.reply_message(
                event.reply_token, 
                TextSendMessage(text="❌ 拆帳失敗，資料庫錯誤", quick_reply=create_quick_reply_buttons())
            )
        finally:
            if conn:
                return_db_connection(conn)
        return

    pattern_general = r'^(?:(\d{4}[-/]\d{1,2}[-/]\d{1,2})\s*)?(.+?)\s*(\d+)$'
    match = re.match(pattern_general, msg)
    
    if match:
        date_str = match.group(1)
        text_content = match.group(2).strip()
        amount = int(match.group(3))
        
        tokens = text_content.split(None, 1)
        final_user_id = sender_id
        item = text_content 
        
        if len(tokens) == 2:
            possible_name = tokens[0]
            remaining_text = tokens[1]
            found_id = get_user_id_by_name(possible_name)
            if found_id:
                final_user_id = found_id
                item = remaining_text 

        created_at_val = "now()" 
        display_date = "今天"
        if date_str:
            try:
                datetime.strptime(date_str, "%Y-%m-%d")
                created_at_val = f"'{date_str} 12:00:00'" 
                display_date = date_str
            except ValueError:
                line_bot_api.reply_message(
                    event.reply_token, 
                    TextSendMessage(text="❌ 日期格式請用 YYYY-MM-DD", quick_reply=create_quick_reply_buttons())
                )
                return

        conn = None
        try:
            conn = get_db_connection()
            cur = conn.cursor()
            
            if created_at_val == "now()":
                cur.execute(
                    "INSERT INTO expenses (user_id, item, amount) VALUES (%s, %s, %s)",
                    (final_user_id, item, amount)
                )
            else:
                cur.execute(
                    "INSERT INTO expenses (user_id, item, amount, created_at) VALUES (%s, %s, %s, %s)",
                    (final_user_id, item, amount, date_str)
                )
                
            conn.commit()
            
            final_user_name = get_user_name(final_user_id, conn)
            if final_user_id == sender_id:
                final_user_name = "你" 

            cur.close()
            
            reply_msg = f"✅ 已記錄！\n📅 時間：{display_date}\n👤 付款：{final_user_name}\n🛒 項目：{item}\n💰 金額：${amount}"
            line_bot_api.reply_message(
                event.reply_token, 
                TextSendMessage(text=reply_msg, quick_reply=create_quick_reply_buttons())
            )
            
        except Exception as e:
            app.logger.error(f"Database Error: {e}")
            line_bot_api.reply_message(
                event.reply_token, 
                TextSendMessage(text="❌ 記帳失敗，資料庫出錯了。", quick_reply=create_quick_reply_buttons())
            )
        finally:
            if conn:
                return_db_connection(conn)
        return

    # === 結算功能（支援簡易與詳細模式）===
    match_settle = re.match(r'^(?:(.+?)\s*)?(詳細)?結算$', msg)
    
    if match_settle:
        specific_name = match_settle.group(1)
        is_detailed = match_settle.group(2) == "詳細"
        conn = None
        
        try:
            conn = get_db_connection()
            cur = conn.cursor()
            
            # === 個人結算 ===
            if specific_name:
                target_uid = get_user_id_by_name(specific_name)
                
                if specific_name == "我":
                    target_uid = sender_id
                    specific_name = get_user_name(sender_id, conn)

                if not target_uid:
                     line_bot_api.reply_message(
                         event.reply_token, 
                         TextSendMessage(
                             text=f"❌ 找不到「{specific_name}」！請確認名字有註冊過。",
                             quick_reply=create_quick_reply_buttons()
                         )
                     )
                     return

                cur.execute("""
                    SELECT created_at, item, amount 
                    FROM expenses 
                    WHERE user_id = %s
                    ORDER BY created_at ASC
                """, (target_uid,))
                details = cur.fetchall()
                
                if not details:
                     line_bot_api.reply_message(
                         event.reply_token, 
                         TextSendMessage(
                             text=f"👤 {specific_name} 目前還沒有消費紀錄喔！",
                             quick_reply=create_quick_reply_buttons()
                         )
                     )
                     return

                reply_text = f"👤 {specific_name} 的消費明細：\n"
                total = 0
                for row in details:
                    dt = row[0]
                    item = row[1]
                    amt = row[2]
                    total += amt
                    date_str = dt.strftime("%m/%d")
                    reply_text += f"{date_str}: {item} ${amt}\n"
                
                reply_text += "----------------\n"
                reply_text += f"💰 個人總支出: ${total}"

            # === 全體結算 ===
            else:
                cur.execute("""
                    SELECT 
                        e.created_at, 
                        COALESCE(u.display_name, e.user_id) as name,
                        e.item, 
                        e.amount,
                        e.user_id
                    FROM expenses e
                    LEFT JOIN users u ON e.user_id = u.user_id
                    ORDER BY e.created_at ASC
                """)
                details = cur.fetchall()
                
                if not details:
                    line_bot_api.reply_message(
                        event.reply_token, 
                        TextSendMessage(
                            text="目前還沒有任何消費紀錄喔！",
                            quick_reply=create_quick_reply_buttons()
                        )
                    )
                    return
                
                cur.execute("SELECT user_id, display_name FROM users")
                users_raw = cur.fetchall()
                user_map = {u[0]: u[1] for u in users_raw}
                
                spending_map = {}
                total_all = 0
                
                # 計算各人總支出
                for row in details:
                    amt = row[3]
                    uid = row[4]
                    total_all += amt
                    spending_map[uid] = spending_map.get(uid, 0) + amt
                
                # 確保所有註冊用戶都在 spending_map 中
                for uid in user_map:
                    if uid not in spending_map:
                        spending_map[uid] = 0
                
                # 計算欠款
                debts = calculate_debts(conn)
                
                # === 簡易模式（預設）===
                if not is_detailed:
                    reply_text = "📊 簡易結算報表\n"
                    reply_text += "================\n"
                    reply_text += f"💰 總支出: ${total_all}\n\n"
                    
                    reply_text += "👤 各人統計：\n"
                    for uid, amt in spending_map.items():
                        name = user_map.get(uid, get_user_name(uid, conn))
                        reply_text += f"{name}: ${amt}\n"
                    
                    # 顯示欠款關係
                    if debts:
                        reply_text += "\n💳 欠款關係：\n"
                        for debtor, creditors in debts.items():
                            for creditor, amount in creditors.items():
                                reply_text += f"{debtor} 欠 {creditor}: ${amount}\n"
                    else:
                        reply_text += "\n✨ 目前沒有未結清的欠款！"
                    
                    reply_text += "\n💡 輸入「詳細結算」查看完整明細"
                
                # === 詳細模式 ===
                else:
                    reply_text = "📝 詳細消費明細：\n"
                    
                    # 按日期分組
                    daily_records = {}
                    for row in details:
                        dt = row[0]
                        date_key = dt.strftime("%Y-%m-%d")
                        if date_key not in daily_records:
                            daily_records[date_key] = []
                        daily_records[date_key].append(row)
                    
                    # 按日期排序（最近的在前）
                    sorted_dates = sorted(daily_records.keys(), reverse=True)
                    
                    # 最多顯示最近 15 天
                    display_dates = sorted_dates[:15]
                    
                    for date in display_dates:
                        dt_obj = datetime.strptime(date, "%Y-%m-%d")
                        date_display = dt_obj.strftime("%m/%d (%a)")
                        
                        # 日期標題
                        reply_text += f"\n📅 {date_display}\n"
                        reply_text += "─────────────\n"
                        
                        # 該日的所有記錄
                        daily_total = 0
                        for row in daily_records[date]:
                            name = row[1]
                            item = row[2]
                            amt = row[3]
                            daily_total += amt
                            reply_text += f"  {name}: {item} ${amt}\n"
                        
                        # 每日小計
                        reply_text += f"  💰 當日小計: ${daily_total}\n"
                    
                    if len(sorted_dates) > 15:
                        reply_text += f"\n... 還有 {len(sorted_dates) - 15} 天的記錄未顯示\n"
                    
                    reply_text += "\n================\n"
                    reply_text += f"💰 總支出: ${total_all}\n\n"
                    
                    reply_text += "👤 各人統計：\n"
                    for uid, amt in spending_map.items():
                        name = user_map.get(uid, get_user_name(uid, conn))
                        reply_text += f"  {name}: ${amt}\n"
                    
                    # 顯示欠款關係
                    if debts:
                        reply_text += "\n💳 欠款關係：\n"
                        for debtor, creditors in debts.items():
                            for creditor, amount in creditors.items():
                                reply_text += f"  {debtor} 欠 {creditor}: ${amount}\n"

            cur.close()
            line_bot_api.reply_message(
                event.reply_token, 
                TextSendMessage(text=reply_text, quick_reply=create_quick_reply_buttons())
            )

        except Exception as e:
            app.logger.error(f"Error: {e}")
            line_bot_api.reply_message(
                event.reply_token, 
                TextSendMessage(text="❌ 結算發生錯誤", quick_reply=create_quick_reply_buttons())
            )
        finally:
            if conn:
                return_db_connection(conn)
        return

    if msg == "清除":
        conn = None
        try:
            conn = get_db_connection()
            cur = conn.cursor()
            cur.execute("DELETE FROM expenses")
            conn.commit()
            cur.close()
            line_bot_api.reply_message(
                event.reply_token, 
                TextSendMessage(
                    text="🗑️ 已清除所有記帳資料！\n一切重新開始 ✨",
                    quick_reply=create_quick_reply_buttons()
                )
            )
        except Exception as e:
            app.logger.error(f"DB Error: {e}")
            line_bot_api.reply_message(
                event.reply_token,
                TextSendMessage(text="❌ 清除失敗，請稍後再試。", quick_reply=create_quick_reply_buttons())
            )
        finally:
            if conn:
                return_db_connection(conn)
        return
    
    # === 預設回覆：當訊息不符合任何指令時 ===
    line_bot_api.reply_message(
        event.reply_token,
        TextSendMessage(
            text="❓ 我不太懂你的意思\n請點選下方按鈕或輸入「說明」查看指令",
            quick_reply=create_quick_reply_buttons()
        )
    )

@app.route("/", methods=['GET'])
def health_check():
    init_db()
    return "Bot is running!", 200

if __name__ == "__main__":
    port = int(os.environ.get('PORT', 5000))
    app.run(host='0.0.0.0', port=port)
