import os
import re
import psycopg2
import logging
from datetime import datetime
from flask import Flask, request, abort
from linebot import LineBotApi, WebhookHandler
from linebot.exceptions import InvalidSignatureError, LineBotApiError
from linebot.models import MessageEvent, TextMessage, TextSendMessage, JoinEvent, FollowEvent

# 設定 Log 顯示 (方便除錯)
logging.basicConfig(level=logging.INFO)
app = Flask(__name__)

# === 1. 從環境變數讀取設定 ===
LINE_CHANNEL_ACCESS_TOKEN = os.environ.get('LINE_CHANNEL_ACCESS_TOKEN')
LINE_CHANNEL_SECRET = os.environ.get('LINE_CHANNEL_SECRET')
DATABASE_URL = os.environ.get('DATABASE_URL')

# 初始化 Line Bot
line_bot_api = LineBotApi(LINE_CHANNEL_ACCESS_TOKEN)
handler = WebhookHandler(LINE_CHANNEL_SECRET)

# === 定義歡迎訊息與指令說明 ===
WELCOME_MSG = (
    "👋 大家好！我是情侶記帳小幫手\n\n"
    "✨ 初次見面請先註冊：\n"
    "👉 輸入「我是 你的名字」\n"
    "(例如：我是 老公)\n\n"
    "📝 【指令大全】\n"
    "1. 記自己 (最常用)：\n"
    "   • 晚餐 200\n"
    "   • 飲料50 (不用空格也行)\n\n"
    "2. 自動拆帳：\n"
    "   • 晚餐 400 幫 150\n"
    "     (總額400，其中150幫對方付)\n"
    "   • 晚餐 400 幫 老公 150\n\n"
    "3. 幫對方記 (全額)：\n"
    "   • 老公 飲料 50\n\n"
    "4. 結算功能 (✨更新)：\n"
    "   • 結算：查看所有人明細\n"
    "   • 老公 結算：只看老公的明細\n\n"
    "5. 其他：\n"
    "   • 清除：刪除資料重新開始\n"
    "   • 說明：顯示此教學"
)

# === 2. 資料庫連線輔助函式 ===
def get_db_connection():
    conn = psycopg2.connect(DATABASE_URL)
    return conn

# === 3. 初始化資料庫 (自動建立使用者表) ===
def init_db():
    try:
        conn = get_db_connection()
        cur = conn.cursor()
        # 建立 users 表 (如果不存在)
        cur.execute("""
            CREATE TABLE IF NOT EXISTS users (
                user_id TEXT PRIMARY KEY,
                display_name TEXT NOT NULL
            );
        """)
        # 確保 expenses 表存在
        cur.execute("""
            CREATE TABLE IF NOT EXISTS expenses (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                user_id TEXT NOT NULL,
                item TEXT NOT NULL,
                amount INTEGER NOT NULL,
                created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('asia/taipei', now())
            );
        """)
        conn.commit()
        cur.close()
        conn.close()
        print("資料庫初始化完成！")
    except Exception as e:
        print(f"資料庫初始化失敗: {e}")

# 應用程式啟動時執行一次初始化
with app.app_context():
    init_db()

# === 4. 輔助函式 ===
# 取得用戶顯示名稱 (User ID -> Name)
def get_user_name(user_id):
    try:
        conn = get_db_connection()
        cur = conn.cursor()
        cur.execute("SELECT display_name FROM users WHERE user_id = %s", (user_id,))
        result = cur.fetchone()
        cur.close()
        conn.close()
        if result:
            return result[0]
    except Exception as e:
        app.logger.error(f"查詢使用者名稱失敗: {e}")
    
    # 資料庫沒有，試著問 LINE
    try:
        profile = line_bot_api.get_profile(user_id)
        return profile.display_name
    except:
        return f"用戶({user_id[:4]})"

# 取得用戶 ID (Name -> User ID)
def get_user_id_by_name(name):
    try:
        conn = get_db_connection()
        cur = conn.cursor()
        cur.execute("SELECT user_id FROM users WHERE display_name = %s", (name,))
        result = cur.fetchone()
        cur.close()
        conn.close()
        if result:
            return result[0]
    except Exception as e:
        app.logger.error(f"查詢 ID 失敗: {e}")
    return None

# 取得「另一半」的 ID (適合只有兩個人的時候)
def get_partner_id(my_user_id):
    try:
        conn = get_db_connection()
        cur = conn.cursor()
        # 找出除了自己以外的所有用戶
        cur.execute("SELECT user_id, display_name FROM users WHERE user_id != %s", (my_user_id,))
        rows = cur.fetchall()
        cur.close()
        conn.close()
        
        # 只有當剩下正好 1 個人時，我們才能確定「另一半」是誰
        if len(rows) == 1:
            return rows[0][0], rows[0][1] # return ID, Name
    except Exception as e:
        app.logger.error(f"查詢另一半失敗: {e}")
    return None, None

@app.route("/callback", methods=['POST'])
def callback():
    signature = request.headers.get('X-Line-Signature', '')
    body = request.get_data(as_text=True)
    app.logger.info(f"Request body: {body}")

    try:
        handler.handle(body, signature)
    except InvalidSignatureError:
        app.logger.error("Invalid signature.")
        abort(400)
    return 'OK'

# === 加入好友時的歡迎詞 (1對1) ===
@handler.add(FollowEvent)
def handle_follow(event):
    line_bot_api.reply_message(event.reply_token, TextSendMessage(text=WELCOME_MSG))

# === 加入群組時的歡迎詞 ===
@handler.add(JoinEvent)
def handle_join(event):
    line_bot_api.reply_message(event.reply_token, TextSendMessage(text=WELCOME_MSG))

@handler.add(MessageEvent, message=TextMessage)
def handle_message(event):
    msg = event.message.text.strip()
    sender_id = event.source.user_id

    # === 功能：小彩蛋 ===
    if msg == "我愛你":
        line_bot_api.reply_message(event.reply_token, TextSendMessage(text="我也愛你們爸爸媽媽 ❤️"))
        return

    # === 功能：顯示說明指令 ===
    if msg in ["說明", "指令", "help", "Help"]:
        line_bot_api.reply_message(event.reply_token, TextSendMessage(text=WELCOME_MSG))
        return
    
    # === 功能 A：註冊名字 (格式：我是 xxx) ===
    if msg.startswith("我是"):
        name = msg[2:].strip()
        if name:
            try:
                conn = get_db_connection()
                cur = conn.cursor()
                # 使用 UPSERT
                cur.execute("""
                    INSERT INTO users (user_id, display_name) 
                    VALUES (%s, %s)
                    ON CONFLICT (user_id) 
                    DO UPDATE SET display_name = EXCLUDED.display_name;
                """, (sender_id, name))
                conn.commit()
                cur.close()
                conn.close()
                line_bot_api.reply_message(event.reply_token, TextSendMessage(text=f"✅ 歡迎 {name}！已記住你的名字。"))
            except Exception as e:
                app.logger.error(f"設定名字失敗: {e}")
                line_bot_api.reply_message(event.reply_token, TextSendMessage(text="❌ 設定失敗，請稍後再試。"))
        return

    # === 功能 B：自動拆帳 (優先判斷) ===
    pattern_split_explicit = r'^(?:(\d{4}[-/]\d{1,2}[-/]\d{1,2})\s*)?(.+?)\s*(\d+)\s*幫\s*(.+?)\s*(\d+)$'
    pattern_split_implicit = r'^(?:(\d{4}[-/]\d{1,2}[-/]\d{1,2})\s*)?(.+?)\s*(\d+)\s*幫\s*(\d+)$'
    
    match_explicit = re.match(pattern_split_explicit, msg)
    match_implicit = re.match(pattern_split_implicit, msg)
    
    if match_explicit or match_implicit:
        target_user_id = None
        target_user_name = None
        
        sender_name = get_user_name(sender_id)

        if match_implicit:
            date_str = match_implicit.group(1)
            item = match_implicit.group(2).strip()
            total_amount = int(match_implicit.group(3))
            split_amount = int(match_implicit.group(4))
            
            target_user_id, target_user_name = get_partner_id(sender_id)
            if not target_user_id:
                line_bot_api.reply_message(event.reply_token, TextSendMessage(text="❌ 無法自動判斷對象！\n如果是多人使用，請指定名字：\n例如：晚餐 400 幫 老公 150"))
                return
        elif match_explicit:
            date_str = match_explicit.group(1)
            item = match_explicit.group(2).strip()
            total_amount = int(match_explicit.group(3))
            target_name_input = match_explicit.group(4).strip()
            split_amount = int(match_explicit.group(5))
            
            target_user_id = get_user_id_by_name(target_name_input)
            if target_user_id:
                target_user_name = target_name_input
            else:
                line_bot_api.reply_message(event.reply_token, TextSendMessage(text=f"❌ 找不到「{target_name_input}」！\n請確認對方有輸入「我是 {target_name_input}」註冊過。"))
                return

        self_amount = total_amount - split_amount
        created_at_val = "now()"
        display_date = "今天"
        if date_str:
            try:
                datetime.strptime(date_str, "%Y-%m-%d")
                created_at_val = f"'{date_str} 12:00:00'"
                display_date = date_str
            except ValueError:
                line_bot_api.reply_message(event.reply_token, TextSendMessage(text="❌ 日期格式請用 YYYY-MM-DD"))
                return

        try:
            conn = get_db_connection()
            cur = conn.cursor()
            
            sql = "INSERT INTO expenses (user_id, item, amount, created_at) VALUES (%s, %s, %s, " + created_at_val + ")" if created_at_val != "now()" else "INSERT INTO expenses (user_id, item, amount) VALUES (%s, %s, %s)"
            
            cur.execute(sql, (sender_id, item, self_amount))
            note_item = f"{item} (需給{sender_name})"
            cur.execute(sql, (target_user_id, note_item, split_amount))
            
            conn.commit()
            cur.close()
            conn.close()
            
            reply_text = (
                f"✅ 自動拆帳完成！\n"
                f"📅 時間：{display_date}\n"
                f"🛒 項目：{item} (總額 ${total_amount})\n"
                f"----------------\n"
                f"👤 {sender_name}：${self_amount}\n"
                f"👤 {target_user_name}：${split_amount}"
            )
            line_bot_api.reply_message(event.reply_token, TextSendMessage(text=reply_text))
            
        except Exception as e:
            app.logger.error(f"DB Error: {e}")
            line_bot_api.reply_message(event.reply_token, TextSendMessage(text="❌ 拆帳失敗，資料庫錯誤"))
        return


    # === 功能 C：一般記帳 (包含幫別人記全額) ===
    pattern_general = r'^(?:(\d{4}[-/]\d{1,2}[-/]\d{1,2})\s*)?(.+?)\s*(\d+)$'
    match = re.match(pattern_general, msg)
    
    if match:
        date_str = match.group(1)
        text_content = match.group(2).strip()
        amount = int(match.group(3))
        
        tokens = text_content.split(None, 1)
        final_user_id = sender_id
        item = text_content 
        
        if len(tokens) == 2:
            possible_name = tokens[0]
            remaining_text = tokens[1]
            found_id = get_user_id_by_name(possible_name)
            if found_id:
                final_user_id = found_id
                item = remaining_text 

        created_at_val = "now()" 
        display_date = "今天"
        if date_str:
            try:
                datetime.strptime(date_str, "%Y-%m-%d")
                created_at_val = f"'{date_str} 12:00:00'" 
                display_date = date_str
            except ValueError:
                line_bot_api.reply_message(event.reply_token, TextSendMessage(text="❌ 日期格式請用 YYYY-MM-DD"))
                return

        try:
            conn = get_db_connection()
            cur = conn.cursor()
            
            if created_at_val == "now()":
                cur.execute(
                    "INSERT INTO expenses (user_id, item, amount) VALUES (%s, %s, %s)",
                    (final_user_id, item, amount)
                )
            else:
                cur.execute(
                    "INSERT INTO expenses (user_id, item, amount, created_at) VALUES (%s, %s, %s, %s)",
                    (final_user_id, item, amount, date_str)
                )
                
            conn.commit()
            
            final_user_name = get_user_name(final_user_id)
            if final_user_id == sender_id:
                final_user_name = "你" 

            cur.close()
            conn.close()
            
            reply_msg = f"✅ 已記錄！\n📅 時間：{display_date}\n👤 付款：{final_user_name}\n🛒 項目：{item}\n💰 金額：${amount}"
            line_bot_api.reply_message(event.reply_token, TextSendMessage(text=reply_msg))
            
        except Exception as e:
            app.logger.error(f"Database Error: {e}")
            line_bot_api.reply_message(event.reply_token, TextSendMessage(text="❌ 記帳失敗，資料庫出錯了。"))
        return

    # === 功能 D：查詢結算 (全體 or 個人) ===
    # Regex: (Name)?\s*結算
    match_settle = re.match(r'^(?:(.+?)\s*)?結算$', msg)
    
    if match_settle:
        specific_name = match_settle.group(1) # None if "結算", "Name" if "Name 結算"
        
        try:
            conn = get_db_connection()
            cur = conn.cursor()
            
            if specific_name:
                # --- 個人結算 ---
                target_uid = get_user_id_by_name(specific_name)
                # Allow "我 結算"
                if specific_name == "我":
                    target_uid = sender_id
                    specific_name = get_user_name(sender_id)

                if not target_uid:
                     line_bot_api.reply_message(event.reply_token, TextSendMessage(text=f"❌ 找不到「{specific_name}」！請確認名字有註冊過。"))
                     return

                cur.execute("""
                    SELECT created_at, item, amount 
                    FROM expenses 
                    WHERE user_id = %s
                    ORDER BY created_at ASC
                """, (target_uid,))
                details = cur.fetchall()
                
                if not details:
                     line_bot_api.reply_message(event.reply_token, TextSendMessage(text=f"👤 {specific_name} 目前還沒有消費紀錄喔！"))
                     return

                reply_text = f"👤 {specific_name} 的消費明細：\n"
                total = 0
                for row in details:
                    dt = row[0]
                    item = row[1]
                    amt = row[2]
                    total += amt
                    date_str = dt.strftime("%m/%d %H:%M")
                    reply_text += f"{date_str}: {item} ${amt}\n"
                
                reply_text += "----------------\n"
                reply_text += f"💰 個人總支出: ${total}"

            else:
                # --- 全體結算 ---
                cur.execute("""
                    SELECT e.created_at, e.user_id, e.item, e.amount 
                    FROM expenses e 
                    ORDER BY e.created_at ASC
                """)
                details = cur.fetchall()
                
                cur.execute("SELECT user_id, display_name FROM users")
                users_raw = cur.fetchall()
                user_map = {u[0]: u[1] for u in users_raw}
                
                if not details:
                    line_bot_api.reply_message(event.reply_token, TextSendMessage(text="目前還沒有任何消費紀錄喔！"))
                    return
                
                reply_text = "📝 全體消費明細：\n"
                spending_map = {} 
                total_all = 0
                
                for row in details:
                    dt = row[0]
                    uid = row[1]
                    item = row[2]
                    amt = row[3]
                    
                    total_all += amt
                    spending_map[uid] = spending_map.get(uid, 0) + amt
                    
                    date_str = dt.strftime("%m/%d %H:%M")
                    name = user_map.get(uid, get_user_name(uid))
                    
                    reply_text += f"{date_str} {name}: {item} ${amt}\n"
                
                reply_text += "----------------\n"
                reply_text += f"💰 總支出: ${total_all}\n"
                
                for uid in user_map:
                    if uid not in spending_map:
                        spending_map[uid] = 0

                reply_text += "👤 各人統計：\n"
                for uid, amt in spending_map.items():
                    name = user_map.get(uid, get_user_name(uid))
                    reply_text += f"{name}: ${amt}\n"

            cur.close()
            conn.close()
            line_bot_api.reply_message(event.reply_token, TextSendMessage(text=reply_text))

        except Exception as e:
            app.logger.error(f"Error: {e}")
            line_bot_api.reply_message(event.reply_token, TextSendMessage(text="❌ 結算發生錯誤"))
        return

    # === 功能 E：清除所有資料 (指令：清除) ===
    if msg == "清除":
        try:
            conn = get_db_connection()
            cur = conn.cursor()
            cur.execute("DELETE FROM expenses")
            conn.commit()
            cur.close()
            conn.close()
            line_bot_api.reply_message(event.reply_token, TextSendMessage(text="🗑️ 已清除所有記帳資料！\n一切重新開始 ✨"))
        except Exception as e:
            app.logger.error(f"DB Error: {e}")
        return

@app.route("/", methods=['GET'])
def health_check():
    return "Bot is running!", 200

if __name__ == "__main__":
    port = int(os.environ.get('PORT', 5000))
    app.run(host='0.0.0.0', port=port)
