import os
import re
import psycopg2
from psycopg2 import pool
import logging
from datetime import datetime
from flask import Flask, request, abort
from linebot import LineBotApi, WebhookHandler
from linebot.exceptions import InvalidSignatureError, LineBotApiError
from linebot.models import (
    MessageEvent, TextMessage, TextSendMessage, JoinEvent, FollowEvent,
    QuickReply, QuickReplyButton, MessageAction  # ← Quick Reply 相關
)

# 設定 Log 顯示
logging.basicConfig(level=logging.INFO)
app = Flask(__name__)

# === 環境變數 ===
LINE_CHANNEL_ACCESS_TOKEN = os.environ.get('LINE_CHANNEL_ACCESS_TOKEN')
LINE_CHANNEL_SECRET = os.environ.get('LINE_CHANNEL_SECRET')
DATABASE_URL = os.environ.get('DATABASE_URL')

line_bot_api = LineBotApi(LINE_CHANNEL_ACCESS_TOKEN)
handler = WebhookHandler(LINE_CHANNEL_SECRET)

# === 🎨 Quick Reply 功能 ===
def create_quick_reply_buttons():
    """建立快速回覆按鈕"""
    return QuickReply(items=[
        QuickReplyButton(
            action=MessageAction(label="早餐", text="早餐")
        ),
        QuickReplyButton(
            action=MessageAction(label="午餐", text="午餐")
        ),
        QuickReplyButton(
            action=MessageAction(label="晚餐", text="晚餐")
        ),
        QuickReplyButton(
            action=MessageAction(label="飲料", text="飲料")
        ),
        QuickReplyButton(
            action=MessageAction(label="交通", text="交通")
        ),
        QuickReplyButton(
            action=MessageAction(label="娛樂", text="娛樂")
        ),
        QuickReplyButton(
            action=MessageAction(label="結算", text="結算")
        ),
        QuickReplyButton(
            action=MessageAction(label="說明", text="說明")
        )
    ])

# === 資料庫連線池 ===
connection_pool = None

def get_connection_pool():
    global connection_pool
    if connection_pool is None:
        connection_pool = psycopg2.pool.SimpleConnectionPool(1, 10, DATABASE_URL)
    return connection_pool

def get_db_connection():
    try:
        pool = get_connection_pool()
        return pool.getconn()
    except Exception as e:
        app.logger.error(f"連線池錯誤: {e}")
        return psycopg2.connect(DATABASE_URL)

def return_db_connection(conn):
    try:
        pool = get_connection_pool()
        pool.putconn(conn)
    except:
        if conn:
            conn.close()

# === 歡迎訊息 ===
WELCOME_MSG = (
    "👋 大家好！我是情侶記帳小幫手\n\n"
    "✨ 初次見面請先註冊：\n"
    "👉 輸入「我是 你的名字」\n"
    "(例如：我是 老公)\n\n"
    "📝 【指令大全】\n"
    "1. 記自己 (最常用)：\n"
    "   • 晚餐 200\n"
    "   • 飲料50 (不用空格)\n\n"
    "2. 自動拆帳：\n"
    "   • 晚餐 400 幫 150\n\n"
    "3. 結算與查詢：\n"
    "   • 結算：看所有人明細\n"
    "   • 老公 結算：只看老公的\n\n"
    "4. 修改與刪除：\n"
    "   • 移除 飲料：刪除最新一筆「飲料」\n"
    "   • 移除最後一筆：刪除剛剛記的那筆\n"
    "   • 清除：全部刪光光\n\n"
    "💡 小技巧：\n"
    "記帳後會出現快速按鈕，點擊即可快速記帳！"
)

# === 資料庫初始化 ===
_db_initialized = False

def init_db():
    global _db_initialized
    if _db_initialized:
        return
    
    try:
        conn = get_db_connection()
        cur = conn.cursor()
        
        cur.execute("""
            CREATE TABLE IF NOT EXISTS users (
                user_id TEXT PRIMARY KEY,
                display_name TEXT NOT NULL
            );
        """)
        
        cur.execute("""
            CREATE TABLE IF NOT EXISTS expenses (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                user_id TEXT NOT NULL,
                item TEXT NOT NULL,
                amount INTEGER NOT NULL,
                created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('asia/taipei', now())
            );
        """)
        
        cur.execute("CREATE INDEX IF NOT EXISTS idx_expenses_user_id ON expenses(user_id);")
        cur.execute("CREATE INDEX IF NOT EXISTS idx_expenses_created_at ON expenses(created_at);")
        cur.execute("CREATE INDEX IF NOT EXISTS idx_expenses_user_created ON expenses(user_id, created_at);")
        
        conn.commit()
        cur.close()
        return_db_connection(conn)
        _db_initialized = True
        app.logger.info("資料庫初始化完成！")
    except Exception as e:
        app.logger.error(f"資料庫初始化失敗: {e}")
        if conn:
            return_db_connection(conn)

# === 輔助函式 ===
def get_user_name(user_id, conn=None):
    should_close = False
    if conn is None:
        conn = get_db_connection()
        should_close = True
    
    try:
        cur = conn.cursor()
        cur.execute("SELECT display_name FROM users WHERE user_id = %s", (user_id,))
        result = cur.fetchone()
        cur.close()
        if result:
            return result[0]
    except Exception as e:
        app.logger.error(f"查詢使用者名稱失敗: {e}")
    finally:
        if should_close:
            return_db_connection(conn)
    
    try:
        profile = line_bot_api.get_profile(user_id)
        return profile.display_name
    except:
        return f"用戶({user_id[:4]})"

def get_user_id_by_name(name):
    conn = None
    try:
        conn = get_db_connection()
        cur = conn.cursor()
        cur.execute("SELECT user_id FROM users WHERE display_name = %s", (name,))
        result = cur.fetchone()
        cur.close()
        if result:
            return result[0]
    except Exception as e:
        app.logger.error(f"查詢 ID 失敗: {e}")
    finally:
        if conn:
            return_db_connection(conn)
    return None

def get_partner_id(my_user_id):
    conn = None
    try:
        conn = get_db_connection()
        cur = conn.cursor()
        cur.execute("SELECT user_id, display_name FROM users WHERE user_id != %s", (my_user_id,))
        rows = cur.fetchall()
        cur.close()
        if len(rows) == 1:
            return rows[0][0], rows[0][1]
    except Exception as e:
        app.logger.error(f"查詢另一半失敗: {e}")
    finally:
        if conn:
            return_db_connection(conn)
    return None, None

@app.route("/callback", methods=['POST'])
def callback():
    init_db()
    signature = request.headers.get('X-Line-Signature', '')
    body = request.get_data(as_text=True)
    app.logger.info(f"Request body: {body}")

    try:
        handler.handle(body, signature)
    except InvalidSignatureError:
        app.logger.error("Invalid signature.")
        abort(400)
    return 'OK'

@handler.add(FollowEvent)
def handle_follow(event):
    line_bot_api.reply_message(
        event.reply_token, 
        TextSendMessage(
            text=WELCOME_MSG,
            quick_reply=create_quick_reply_buttons()  # ← 加入好友時也顯示快速按鈕
        )
    )

@handler.add(JoinEvent)
def handle_join(event):
    line_bot_api.reply_message(
        event.reply_token,
        TextSendMessage(
            text=WELCOME_MSG,
            quick_reply=create_quick_reply_buttons()  # ← 加入群組時也顯示快速按鈕
        )
    )

@handler.add(MessageEvent, message=TextMessage)
def handle_message(event):
    msg = event.message.text.strip()
    sender_id = event.source.user_id

    # === 小彩蛋 ===
    if msg == "我愛你":
        line_bot_api.reply_message(
            event.reply_token,
            TextSendMessage(
                text="我也愛你們爸爸媽媽 ❤️",
                quick_reply=create_quick_reply_buttons()
            )
        )
        return

    # === 說明 ===
    if msg in ["說明", "指令", "help", "Help"]:
        line_bot_api.reply_message(
            event.reply_token,
            TextSendMessage(
                text=WELCOME_MSG,
                quick_reply=create_quick_reply_buttons()
            )
        )
        return
    
    # === 註冊名字 ===
    if msg.startswith("我是"):
        name = msg[2:].strip()
        if name:
            conn = None
            try:
                conn = get_db_connection()
                cur = conn.cursor()
                cur.execute("""
                    INSERT INTO users (user_id, display_name) 
                    VALUES (%s, %s)
                    ON CONFLICT (user_id) 
                    DO UPDATE SET display_name = EXCLUDED.display_name;
                """, (sender_id, name))
                conn.commit()
                cur.close()
                line_bot_api.reply_message(
                    event.reply_token,
                    TextSendMessage(
                        text=f"✅ 歡迎 {name}！已記住你的名字。",
                        quick_reply=create_quick_reply_buttons()
                    )
                )
            except Exception as e:
                app.logger.error(f"設定名字失敗: {e}")
                line_bot_api.reply_message(event.reply_token, TextSendMessage(text="❌ 設定失敗，請稍後再試。"))
            finally:
                if conn:
                    return_db_connection(conn)
        return

    # === 一般記帳（簡化版，完整版請參考原始檔案）===
    pattern_general = r'^(?:(\d{4}[-/]\d{1,2}[-/]\d{1,2})\s*)?(.+?)\s*(\d+)$'
    match = re.match(pattern_general, msg)
    
    if match:
        date_str = match.group(1)
        text_content = match.group(2).strip()
        amount = int(match.group(3))
        
        tokens = text_content.split(None, 1)
        final_user_id = sender_id
        item = text_content 
        
        if len(tokens) == 2:
            possible_name = tokens[0]
            remaining_text = tokens[1]
            found_id = get_user_id_by_name(possible_name)
            if found_id:
                final_user_id = found_id
                item = remaining_text 

        display_date = "今天" if not date_str else date_str

        conn = None
        try:
            conn = get_db_connection()
            cur = conn.cursor()
            
            if not date_str:
                cur.execute(
                    "INSERT INTO expenses (user_id, item, amount) VALUES (%s, %s, %s)",
                    (final_user_id, item, amount)
                )
            else:
                cur.execute(
                    "INSERT INTO expenses (user_id, item, amount, created_at) VALUES (%s, %s, %s, %s)",
                    (final_user_id, item, amount, date_str)
                )
                
            conn.commit()
            
            final_user_name = get_user_name(final_user_id, conn)
            if final_user_id == sender_id:
                final_user_name = "你" 

            cur.close()
            
            reply_msg = f"✅ 已記錄！\n📅 時間：{display_date}\n👤 付款：{final_user_name}\n🛒 項目：{item}\n💰 金額：${amount}"
            
            # 🎨 重點：回覆時加上 Quick Reply
            line_bot_api.reply_message(
                event.reply_token,
                TextSendMessage(
                    text=reply_msg,
                    quick_reply=create_quick_reply_buttons()  # ← 這裡加上快速按鈕
                )
            )
            
        except Exception as e:
            app.logger.error(f"Database Error: {e}")
            line_bot_api.reply_message(event.reply_token, TextSendMessage(text="❌ 記帳失敗，資料庫出錯了。"))
        finally:
            if conn:
                return_db_connection(conn)
        return

    # === 結算（簡化版）===
    if msg == "結算":
        conn = None
        try:
            conn = get_db_connection()
            cur = conn.cursor()
            
            cur.execute("""
                SELECT 
                    e.created_at, 
                    COALESCE(u.display_name, e.user_id) as name,
                    e.item, 
                    e.amount,
                    e.user_id
                FROM expenses e
                LEFT JOIN users u ON e.user_id = u.user_id
                ORDER BY e.created_at ASC
            """)
            details = cur.fetchall()
            
            if not details:
                line_bot_api.reply_message(
                    event.reply_token,
                    TextSendMessage(
                        text="目前還沒有任何消費紀錄喔！",
                        quick_reply=create_quick_reply_buttons()
                    )
                )
                return
            
            cur.execute("SELECT user_id, display_name FROM users")
            users_raw = cur.fetchall()
            user_map = {u[0]: u[1] for u in users_raw}
            
            reply_text = "📝 全體消費明細：\n"
            spending_map = {}
            total_all = 0
            
            for row in details:
                dt = row[0]
                name = row[1]
                item = row[2]
                amt = row[3]
                uid = row[4]
                
                total_all += amt
                spending_map[uid] = spending_map.get(uid, 0) + amt
                
                date_str = dt.strftime("%m/%d")
                reply_text += f"{date_str} {name}: {item} ${amt}\n"
            
            reply_text += "----------------\n"
            reply_text += f"💰 總支出: ${total_all}\n"
            
            reply_text += "👤 各人統計：\n"
            for uid, amt in spending_map.items():
                name = user_map.get(uid, get_user_name(uid, conn))
                reply_text += f"{name}: ${amt}\n"

            cur.close()
            
            # 🎨 結算時也加上 Quick Reply
            line_bot_api.reply_message(
                event.reply_token,
                TextSendMessage(
                    text=reply_text,
                    quick_reply=create_quick_reply_buttons()
                )
            )

        except Exception as e:
            app.logger.error(f"Error: {e}")
            line_bot_api.reply_message(event.reply_token, TextSendMessage(text="❌ 結算發生錯誤"))
        finally:
            if conn:
                return_db_connection(conn)
        return

@app.route("/", methods=['GET'])
def health_check():
    init_db()
    return "Bot is running!", 200

if __name__ == "__main__":
    port = int(os.environ.get('PORT', 5000))
    app.run(host='0.0.0.0', port=port)
